; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:PaperS3]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
build_flags = 
	-DESP32S3
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DMAX_BUFFERED_PIXELS=8192
lib_deps = 
	M5Unified=https://github.com/m5stack/M5Unified
	bblanchon/ArduinoJson@^7.0.4
	bitbank2/PNGdec@^1.1.6
	bitbank2/JPEGDEC@^1.8.4
	bitbank2/FastEPD@^1.4.1
monitor_speed = 115200
